blank_issues_enabled: false
contact_links:
  - name: Community
    url: https://discord.gg/G23MvytuSy
    about: If you are interested in talking with members of the WESL community, join us on discord.
